&id002 !!python/object/new:utility.AttrDict
dictitems:
  data: &id001 !!python/object/new:utility.AttrDict
    dictitems:
      celebA_center_crop: false
    state: *id001
  method: giraffe
  model:
    background_generator: simple
state: *id002
